Add ConnectivityUtil
GrapheneOS/platform_frameworks_base pull request #28
Opened 2024-10-15 05:37 UTC by u-fred

Port of https://github.com/GrapheneOS/platform_frameworks_base/pull/27

Required by https://github.com/GrapheneOS/platform_packages_modules_Connectivity/pull/17 and https://github.com/GrapheneOS/platform_packages_modules_Connectivity/pull/18

2024-11-17 15:17 UTC, muhomorr requested changes

2024-11-17 15:17 UTC, muhomorr commented on core/java/android/ext/ConnectivityUtil.java
> +        return Settings.Secure.getInt(cr, Settings.Secure.ALWAYS_ON_VPN_LOCKDOWN, 0) == 1;
There's `Settings.Secure.getIntForUser()`, no need to create a new Context.

2024-11-17 15:17 UTC, muhomorr commented on core/java/android/ext/ConnectivityUtil.java
> +        if (isSystem(context, uid)) {
ALWAYS_ON_VPN_LOCKDOWN check should be done first, it's much faster than isSystem() check in most cases.

2025-03-13 23:13 UTC, closed without merging

2025-03-14 00:53 UTC, thestinger commented
This will need to be reopened against 15-qpr2 and possibly ported to it.